"""Identity helpers for model-visible events generated by Yoke."""

from __future__ import annotations

from yoke.agent.models import ConversationEntry
from yoke.agent.models import Message

COMMAND_COMPLETION_EVENT = "command_completion"
INTERNAL_EVENT_METADATA_KEY = "yoke_internal_event"
COMMAND_COMPLETION_NOTICE_PREFIX = "[Automatic command lifecycle notice from Yoke]"


def is_command_completion_message(message: Message | None) -> bool:
    """Return whether a message is a Yoke command-completion notice."""
    return bool(
        message is not None
        and (message.plain_text_content or "").startswith(
            COMMAND_COMPLETION_NOTICE_PREFIX
        )
    )


def is_command_completion_entry(entry: ConversationEntry) -> bool:
    """Recognize current metadata and legacy text-only completion notices."""
    return entry.metadata.get(
        INTERNAL_EVENT_METADATA_KEY
    ) == COMMAND_COMPLETION_EVENT or is_command_completion_message(entry.message)
